### ISSUE TITLE
Suggestion: Ability to Quickly Remove References

### ISSUE THREAD

**Issue by aolszowka** [denismarkelov/AssemblyVisualizer#6]
Hi,

First off great plug-in, I use it quite often.

The ability to "Remove Selected" is a very useful one (especially when trying to filter out "noise" in the Dependency Graph). A useful addition would be the ability to show a listing of all the dependencies and then allow for a check box selection for removing them. Another useful feature to combine with the above would be to filter "System" dependencies (IE elements that are considered Shipped with .NET).

Before I start groveling in code to add this functionality I just want to make sure it wasn't on someone else's radar. Currently you can kinda mock this up by Searching for elements (for example "System.") and then removing those as it selects those elements.

Thanks

**Comment by manunt** [comment]
Sounds good!

**Comment by Trass3r** [comment]
Yes the System assemblies really clutter the view.
Also it would be nice to select assemblies via dragging a rectangle with the mouse and remove assemblies with the delete key.
