### ISSUE TITLE
Cannot visualize type hierarchy

### ISSUE THREAD

**Issue by Przemyslaw-W** [denismarkelov/AssemblyVisualizer#8]
Downloaded Reflector 8.5 trial, installed recent release (1.0.2.1) of this addin.
Open Microsoft.CodeAnalysis.CSharp.dll in reflector, navigate to Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode class and try to visualize its descendants. Error shows up. See http://screencast.com/t/Vlda21mcFO

**Comment by Trojaner25** [comment]
same here
